valid_email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
max_length_name_20: 20
min_length_email_20: 20
max_length_email_255: 255
min_length_password_6: 6
gravatar_url: https://secure.gravatar.com/avatar/
